import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/front/src/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex lg:mx-20`}
      >
        <ContextProvider>
          <div className="w-full lg:mr-20">
            {children}
          </div>
          <div className="sidebar__aside hidden lg:inline">
            <div className="banner h-full" />
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
